---
apiVersion: v1
kind: Secret
metadata:
  name: rhsummit23-quarkus-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevRHEL/rhsummit23-quarkus-gitops